language: node_js
node_js:
  # - "6"
  # - "6.2"
  # - "6.1"
  # - "6.0"
  - "5"
  # - "5.11"
  # - "5.10"
  # - "5.9"
  # - "5.8"
  # - "5.7"
  # - "5.6"
  # - "5.5"
  # - "5.4"
  # - "5.3"
  # - "5.1"
  # - "5.0"
  # 4.x fails due to lack of support for rest parameters.
  # - "4"
  # - "4.4"
  # - "4.3"
  # - "4.2"
  # - "4.1"
  # - "4.0"
  # - "0.12" # Doesn't understand string template literals (fails in gulpfile.js).
  # - "0.11"
  # - "0.10" # Doesn't understand string template literals (fails in gulpfile.js).
  # - "0.8" # Error: No compatible version found: babel-preset-es2015@'^6.6.0', del@'^2.2.0', and gulp@'^3.9.1'
  # - "0.6" # Error: No compatible version found: babel-preset-es2015@'^6.6.0' and gulp@'^3.9.1'
  # - "iojs"
script: npm run travisci
env:
  matrix:
    # - TZ=America/Adak
    # - TZ=America/Anchorage
    # - TZ=America/Boise
    - TZ=America/Chicago
    - TZ=America/Denver
    # - TZ=America/Detroit
    # - TZ=America/Indiana/Indianapolis
    # - TZ=America/Indiana/Knox
    # - TZ=America/Indiana/Marengo
    # - TZ=America/Indiana/Petersburg
    # - TZ=America/Indiana/Tell_City
    # - TZ=America/Indiana/Vevay
    # - TZ=America/Indiana/Vincennes
    # - TZ=America/Indiana/Winamac
    # - TZ=America/Juneau
    # - TZ=America/Kentucky/Louisville
    # - TZ=America/Kentucky/Monticello
    # - TZ=America/Los_Angeles
    # - TZ=America/Menominee
    # - TZ=America/Metlakatla
    # - TZ=America/New_York
    # - TZ=America/Nome
    # - TZ=America/North_Dakota/Beulah
    # - TZ=America/North_Dakota/Center
    # - TZ=America/North_Dakota/New_Salem
    # - TZ=America/Phoenix
    # - TZ=America/Sitka
    # - TZ=America/Yakutat
    # - TZ=Pacific/Honolulu
